### ISSUE TITLE
Add a close menu button for mobile menu

### ISSUE THREAD

**Issue by KTS915** [ClassicPress/ClassicPress-Themes#10]
This adds a close button via SVG in the `header.php` template, modifies the javascript in `/js/scripts.js` so that the button toggles between the current and the new button on open and close, and adds the relevant CSS in `styles.css` to make it all fit in with the rest of the theme.

The attached zip includes only those files, and not the whole theme.

[mobile-button-mods.zip](https://github.com/ClassicPress/ClassicPress-Themes/files/2569495/mobile-button-mods.zip)

**Comment by striebwj** [comment]
Pushed changes.

**Comment by KTS915** [comment]
@nylen suggested on Slack that screenshots would be helpful so that you can see the difference. So here's a screenshot showing the new Close button in action.

![screenshot from 2018-11-11 14-48-04](https://user-images.githubusercontent.com/4127662/48317473-f1528a00-e5c0-11e8-994d-2fa8bc1b92c5.png)

**Comment by nylen** [comment]
I've deployed the latest version of the theme (what's in this repository) on test.classicpress.net, and the mobile menu is not working for me (not expanding when I click the hamburger icon).

Same behavior on beta.classicpress.net although I have not made any changes there.

Note that we need to update the cache buster string each time the CSS and JavaScript are changed, see https://github.com/ClassicPress/ClassicPress-Themes/commit/096320c7b833ba55bd95017b3117d5c517ff0a2d.

Going forward it will be much nicer if we can collaborate using git and GitHub so that we know we are on the all same version of the code.  I don't know exactly why the mobile menu is not working on the latest version of the theme but I suspect that something hasn't been copied correctly and is outdated.

**Comment by KTS915** [comment]
It's working for me. But I don't see the latest version of the mobile menu. It doesn't have the close button. So maybe you have reverted.

**Comment by KTS915** [comment]
Note also that if you change the view from desktop to mobile width, you will need to refresh the page to make the javascript fire. It is, of course, possible to add something to make this happen automatically, but I am happy to leave that call to you.

**Comment by nylen** [comment]
I think what you have locally is out of sync from what's in the repository.  Unfortunately it's not really possible to tell why, or what specifically the problem is, from here.  This is why we use `git` to manage source code - it solves this problem and several others.

I think we should add the JS to handle window resizing.

We also need to make the mobile menu work with JavaScript disabled - right now it is not possible to access the navigation.  This can be accomplished by showing the menu contents on small viewports by default, and hiding them via JavaScript.

**Comment by nylen** [comment]
> Note also that if you change the view from desktop to mobile width, you will need to refresh the page to make the javascript fire. 

Thanks, this fixed the issue I was having with the mobile menu not expanding/collapsing.

**Comment by KTS915** [comment]
Yes, I thought that's what it was. Do you have code that you like to use to detect change in viewport size? I can't say that I have ever found any that was truly satisfactory.

**Comment by nylen** [comment]
It should be possible to do this in a way that doesn't require a resize listener.  Something like this:

- CSS says that mobile menu content is expanded / visible by default
- JS applies a class to the `body` or `html` element on load, and the presence of this class causes the mobile menu content to be collapsed / hidden by default, and the appropriate icon shown
- Clicking the menu icon expands the mobile menu content; clicking the X icon collapses it.

**Comment by KTS915** [comment]
>We also need to make the mobile menu work with JavaScript disabled - right now it is not possible to access the navigation.

I am just about to go to bed, but I thought I'd better point out a problem here. Michelle's design didn't incorporate a search box. So I forced it into the bottom of the first submenu using jQuery. So if you want navigation to work without javascript, you will need to add a search box somewhere using PHP and HTML. Obviously that's possible when you know how the final thing will look, but it's a bit difficult otherwise. Or else not have search when js is disabled.

**Comment by KTS915** [comment]
I am not convinced about the need to add code for viewport resize. I don't thing most people do that; it's just developers. And I still haven't found any code I like for that. So I will punt that to you

**Comment by nylen** [comment]
I think this might take a little bit of restructuring, but the only width-specific that should be needed is in CSS media queries.

I'm not going to do anything about it right now though, because we still have an unexplained / unresolved issue with the (X) button not appearing in the menu.

**Comment by KTS915** [comment]
So far as the issue of displaying menu items when JS is disabled, I think it's best just to not bother with search when that happens. On that basis, here is the updated `scripts.js` file, and these are the relevant CSS fixes for `style.css`. I have discussed them already with @senlin, who has been extremely helpful, and they should also take care of the issue mentioned here: https://github.com/ClassicPress/ClassicPress-Themes/issues/19#issuecomment-437876833

In the section headed `@media(min-width:801px) {` find the selectors ``.sub-menu`, `.menu li a`, and `input[type="search"] {` The relevant CSS for each one is as follows:
```
.sub-menu {
	display: inline;
	flex-direction: column;
	position: absolute;
	margin-top: 12px;
	background: #006b81;
	border-width: 0 1px 1px 1px;
	border-color: rgba(0,0,0,0.15);
	border-style: solid;
}

.menu li a {
	display: flex;
	flex-grow: 1;
	padding: 0.75em  1.5em;
}

input[type="search"] {
	max-width: 100%;
	padding: 0.75em;
	border-radius: 6px;
}
```

Beneath `.submenu` also add the following:
`.sub-menu li a {
	padding-left: 1em;
}`

[scripts.js.zip](https://github.com/ClassicPress/ClassicPress-Themes/files/2572675/scripts.js.zip)

**Comment by KTS915** [comment]
The `scripts.js` file I have uploaded should also fix the X button not appearing. If it doesn't, then I'll check the `header.php` and `style.css` file to figure out what's missing.

**Comment by nylen** [comment]
This seems fixed to me with Tim's latest changes (commit c3facf9); please re-open if you're still seeing it on https://test.classicpress.net/.

I have a couple more improvements I'd like to make here; I'll open a separate issue for that.
