### ISSUE TITLE
Use a style sheet language?

### ISSUE THREAD

**Issue by striebwj** [ClassicPress/ClassicPress-Themes#2]
Do we use something like Sass for development of the theme?

**Comment by nylen** [comment]
Build steps suck, but SASS is nice to use.

I think we can leave this up to whoever's doing the work.  If we do end up using SASS we should include some documentation in the readme about how to build the styles.

**Comment by dixonge** [comment]
In the spirit of KISS, can we somehow include it but make it optional, like composer? Ready to go if you want, but not required? Devs will probably love it, but not so much a mom-n-pop business.

**Comment by nylen** [comment]
Not really, because once you start using SASS you have to keep using it instead of updating the raw CSS, and the build step needs to be run for each change.

If I were doing the work here I would stick with raw CSS. I'm not though, at least not at this point, so I'll just say "if you add it, please document how to build it also".

**Comment by striebwj** [comment]
Decided to stick with raw CSS.
